### ISSUE TITLE
Test failure in 0.184.2 version

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1549]
@nikhilwoodruff, when I update to the 0.184.2 version and run `make test` I get this:
```
policyengine-us% grep version setup.py 
    version="0.184.2",

policyengine-us% make test            
coverage run -a --branch -m policyengine_core.scripts.policyengine_command test policyengine_us/tests/policy/ -c policyengine_us
ERROR:policyengine_core.taxbenefitsystems.tax_benefit_system:Unable to load OpenFisca variables from file "/Users/mrh/work/policyengine-us/policyengine_us/variables/input/geography.py"
Traceback (most recent call last):
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/policyengine_command.py", line 133, in <module>
    sys.exit(main())
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/policyengine_command.py", line 124, in main
    return sys.exit(main(parser))
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/run_test.py", line 18, in main
    tax_benefit_system = build_tax_benefit_system(
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/__init__.py", line 41, in build_tax_benefit_system
    country_package = importlib.import_module(country_package_name)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/mrh/work/policyengine-us/policyengine_us/__init__.py", line 10, in <module>
    from policyengine_us.system import (
  File "/Users/mrh/work/policyengine-us/policyengine_us/system.py", line 41, in <module>
    system = CountryTaxBenefitSystem()
  File "/Users/mrh/work/policyengine-us/policyengine_us/system.py", line 31, in __init__
    super().__init__(entities)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 118, in __init__
    self.add_variables_from_directory(self.variables_dir)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 337, in add_variables_from_directory
    self.add_variables_from_directory(subdirectory)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 334, in add_variables_from_directory
    self.add_variables_from_file(py_file)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 277, in add_variables_from_file
    self.add_variable(pot_variable)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 179, in add_variable
    return self.load_variable(variable, update=False)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 164, in load_variable
    variable = variable_class(baseline_variable=baseline_variable)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/variables/variable.py", line 248, in __init__
    raise ValueError(
ValueError: Unexpected attributes in definition of variable "medicaid_rating_area": 'hidden_input'
make: *** [test] Error 1
```

What's the problem?

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1549:
> `hidden_input` was added in `policyengine-core==1.10.15`. We should hard-pin that instead of the current policyengine-core>=1.10,<1.11.

Thanks for the tip, but why wasn't this done in pull request #1547?
